;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #1e1e2e
background-alt = #585b70
foreground = #cdd6f4
primary = #a6e3a1
secondary = #94e2d5
alert = #f38ba8
disabled = #7f849c

#[global/wm]
#margin-bottom = 10

[bar/mybar]
width = 100%
height = 20pt
radius = 0

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt
border-size = 0pt
border-color = #00000000

padding-left = 0
padding-right = 1
module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

;font-0 = monospace;2
font-0 = NotoSansMono Nerd Font Mono:style=ExtraCondensed Medium;2
font-1 = Source Han Sans JP,源ノ角ゴシック JP:style=Regular;2

modules-left = xworkspaces xwindow
modules-right = mpris pulseaudio wlan eth brightness battery date menu-power

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

tray-position = center
tray-background = ${root.background}
tray-foreground = ${root.foreground}

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = false

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%


[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.disabled}
click-right = pavucontrol


[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = ${env:BAR_WIFI_ON}
label-disconnected = ${env:BAR_WIFI_OFF}
hidden=true

[module/eth]
inherit = network-base
interface-type = wired
label-connected = ${env:BAR_ETH_ON}
label-disconnected = ${env:BAR_ETH_OFF}
hidden=true


[module/battery]
type = internal/battery
full-at = 99
low-at = 30
adapter = AC0
battery = BAT0
poll-interval = 5

format-charging = <label-charging>
format-discharing = <label-discharging>
format-full = <label-full>
format-low = <label-low>

label-charging = ${env:BAR_BAT_CHARGE}
label-discharging =  ${env:BAR_BAT_DISCHARGE}
label-full = ${env:BAR_BAT_FULL}
label-low = ${env:BAR_BAT_LOW}


[module/date]
type = internal/date
interval = 1

date = %H:%M
date-alt = %Y-%m-%d %a %H:%M:%S

label = %date%
label-foreground = ${colors.primary}


[module/menu-power]
type = custom/menu
expand-right = false
label-open = "⏻"
label-close = "  "
;label-separator = |

menu-0-0 = "  "
menu-0-0-exec = systemctl suspend

menu-0-1 = "  "
menu-0-1-exec = systemctl reboot

menu-0-2 = " ⏻ "
menu-0-2-exec = systemctl poweroff


[module/mpris]
type = custom/script
tail = true
exec = ~/.config/polybar/scripts/mpris_status.sh

format = <label>
label = ${env:BAR_MPRIS}

click-left = playerctl play-pause
click-right = playerctl next
click-middle = playerctl position 0 && playerctl previous
double-click-middle = playerctl stop

scroll-up = playerctl position 5+
scroll-down = playerctl position 5-


[module/brightness]
type = custom/script
tail = true

exec = ~/.config/polybar/scripts/brightness.sh
label = ${env:BAR_BRIGHTNESS}

click-left = brightnessctl -q s 5%+
click-right = brightnessctl -q s 5%-
scroll-up = brightnessctl -q s 1+
scroll-down = brightnessctl -q s 1-


[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
