[greeter]
font-name = Source Han Sans JP 10
background = /usr/share/wallpapers/Aurora_Borealis_3.jpg
screensaver-timeout = 30
theme-name = Catppuccin-Mocha-Standard-Green-Dark
icon-theme-name = Papirus-Dark
default-user-image = /usr/share/icons/logins/Ayaka.png

